name: ezeknekjolesz
favicon: null
layout_spectrum: 0.13023645291104913
typography_spectrum: 0.62726
title: Ezeknek... jรณ lesz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#017143'
    - '#be152c'
    - '#000000'
    - '#ccba1a'
    - '#89770b'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
